keystone::roles::admin::admin_project_domain: ldap
swift:
  swift_operator_roles:
    - Member
    - admin
    - SwiftOperator
    - _member_
::murano::external_network: ext_float
configuration:
  murano_config:
    'networking/external_network':
      value: ext_float
  service:
      murano-api:
          ensure: running
